#source 'https://github.com/Fiser33/iOSTiledViewerSpec.git'
use_frameworks!

target 'iOSTiledViewer_Example' do
    pod 'iOSTiledViewer', :path => '../'
end

post_install do |installer|
    optimization = 'SWIFT_OPTIMIZATION_LEVEL'
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Release'
                config.build_settings[optimization] = '-Owholemodule'
            end
        end
    end
end
